"""Singleton in-memory group state — shared across all phone viewers.

Every viewer (each phone instance in the demo) polls /state and renders the
same snapshot. Mutations (send message, approve, swap alternate, dismiss idea,
wipe) happen via the dedicated endpoints in server.py.

For a hackathon demo this is fine; restart server.py = clean slate.
"""
from __future__ import annotations

import asyncio
from dataclasses import asdict, dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Literal
from uuid import uuid4

from lib import matching


# ──────────────────────── data shapes ────────────────────────


@dataclass
class ChatMessage:
    id: str
    kind: Literal["user", "reactive", "proposal", "celebration"]
    ts: str
    # user fields
    author_id: str | None = None
    text: str | None = None
    # reactive fields
    parent_id: str | None = None
    query: str | None = None
    matches: list[dict] = field(default_factory=list)
    proposal_id: str | None = None
    event_title: str | None = None


ProposalStatus = Literal["pending", "booking", "booked", "skipped"]


@dataclass
class Proposal:
    id: str
    window: dict
    event: dict
    alternates: list[dict]
    approvals: dict[str, bool]  # user_id → approved?
    status: ProposalStatus = "pending"
    created_at: str = ""
    booking: dict | None = None  # set after booking attempt
    # Friend-voice headline rendered above the event card. Generated by
    # `proposal_node` via ASI:One; None means the bubble renders body-only.
    headline: str | None = None


@dataclass
class Idea:
    event: dict
    source: Literal["reactive", "proposal", "alternate"]
    score: int
    seen_at: str
    interested: list[str] = field(default_factory=list)  # user ids who clicked I'm in / proposed
    hidden: list[str] = field(default_factory=list)  # user ids who clicked Hide (per-user)
    dismissed: bool = False  # global removal (e.g. on book) — not the same as a per-user hide


# ──────────────────────── store ────────────────────────


class GroupState:
    def __init__(self) -> None:
        self.lock = asyncio.Lock()
        self.messages: list[ChatMessage] = []
        self.current_proposal: Proposal | None = None
        # nest_warmth: 0–30. Decays as the group goes silent, restores to 30
        # when a plan books. The carrot version of an "expiry countdown" —
        # the chat never dies, but its nest can go cold.
        self.nest_warmth: int = 6
        self.last_booking: dict | None = None
        self.ideas: list[Idea] = []  # ordered by score desc

    # ─── snapshot ───

    def snapshot(self) -> dict:
        return {
            "messages": [asdict(m) for m in self.messages],
            "current_proposal": asdict(self.current_proposal) if self.current_proposal else None,
            "nest_warmth": self.nest_warmth,
            "nest_max": 30,
            "expiry_days": self.nest_warmth,
            "last_booking": self.last_booking,
            "ideas": [asdict(i) for i in self.ideas if not i.dismissed],
            "users": [{"id": u["id"], "name": u["name"], "color": u["avatar_color"]} for u in matching.load_users()],
        }

    # ─── helpers ───

    @staticmethod
    def _now_iso() -> str:
        return datetime.now(timezone.utc).isoformat()

    def _user_ids(self) -> list[str]:
        return [u["id"] for u in matching.load_users()]

    # ─── ranking ───
    #
    # Every mutation that touches the ideas panel funnels through `_rerank` so
    # the LangGraph `ranking_graph` is the single source of truth for panel
    # order. That means dedupe, composite scoring, and (later) clustering all
    # happen in one swappable place.

    def _ideas_to_dicts(self) -> list[dict]:
        return [asdict(i) for i in self.ideas]

    def _ideas_from_dicts(self, dicts: list[dict]) -> list[Idea]:
        out: list[Idea] = []
        for d in dicts:
            out.append(
                Idea(
                    event=d.get("event") or {},
                    source=d.get("source") or "reactive",  # type: ignore[arg-type]
                    score=int(d.get("score") or 0),
                    seen_at=d.get("seen_at") or self._now_iso(),
                    interested=list(d.get("interested") or []),
                    hidden=list(d.get("hidden") or []),
                    dismissed=bool(d.get("dismissed") or False),
                )
            )
        return out

    def _rerank(
        self,
        *,
        additions: list[dict] | None = None,
        interactions: list[dict] | None = None,
    ) -> None:
        from agents.graph.workflow import ranking_graph

        s = ranking_graph().invoke({
            "ideas": self._ideas_to_dicts(),
            "additions": additions or [],
            "interactions": interactions or [],
        })
        self.ideas = self._ideas_from_dicts(s.get("ideas") or [])

    def _add_idea(self, event: dict, source: str, score: int = 0) -> None:
        if not event.get("id"):
            return
        self._rerank(additions=[{"event": event, "source": source, "base_score": int(score)}])

    def _mirror_interest(self, event_id: str | None, user_id: str | None, *, on: bool = True) -> None:
        if not event_id or not user_id:
            return
        kind = "interest_on" if on else "interest_off"
        self._rerank(interactions=[{"event_id": event_id, "user_id": user_id, "kind": kind}])

    def _mirror_hide(self, event_id: str | None, user_id: str | None, *, on: bool = True) -> None:
        if not event_id or not user_id:
            return
        kind = "hide_on" if on else "hide_off"
        self._rerank(interactions=[{"event_id": event_id, "user_id": user_id, "kind": kind}])

    # ─── mutations ───

    async def send_message(self, author_id: str, text: str) -> ChatMessage:
        async with self.lock:
            msg = ChatMessage(
                id=f"m_{uuid4().hex[:8]}",
                kind="user",
                ts=self._now_iso(),
                author_id=author_id,
                text=text,
            )
            self.messages.append(msg)
            return msg

    async def add_reactive(self, parent_id: str, query: str, matches: list[dict]) -> ChatMessage:
        async with self.lock:
            msg = ChatMessage(
                id=f"r_{uuid4().hex[:8]}",
                kind="reactive",
                ts=self._now_iso(),
                parent_id=parent_id,
                query=query,
                matches=matches,
            )
            self.messages.append(msg)
            for e in matches:
                self._add_idea(e, source="reactive", score=int(e.get("_score", 0)) or 1)
            return msg

    async def set_proposal(
        self,
        *,
        window: dict,
        event: dict,
        alternates: list[dict],
        headline: str | None = None,
    ) -> Proposal:
        async with self.lock:
            user_ids = self._user_ids()
            proposal = Proposal(
                id=f"p_{uuid4().hex[:8]}",
                window=window,
                event=event,
                alternates=alternates,
                approvals={uid: False for uid in user_ids},
                status="pending",
                created_at=self._now_iso(),
                headline=headline,
            )
            self.current_proposal = proposal
            self._add_idea(event, source="proposal", score=int(event.get("_score", 0)) or 5)
            for alt in alternates:
                self._add_idea(alt, source="alternate", score=int(alt.get("_score", 0)) or 2)
            return self.current_proposal

    async def approve(self, user_id: str) -> Proposal | None:
        async with self.lock:
            p = self.current_proposal
            if not p or p.status != "pending":
                return p
            if user_id not in p.approvals:
                return p
            p.approvals[user_id] = True
            self._mirror_interest(p.event.get("id"), user_id, on=True)
            return p

    def all_approved(self) -> bool:
        p = self.current_proposal
        return bool(p and p.status == "pending" and all(p.approvals.values()))

    async def mark_booking_in_progress(self) -> None:
        async with self.lock:
            if self.current_proposal:
                self.current_proposal.status = "booking"

    async def complete_booking(self, result: dict) -> None:
        async with self.lock:
            if self.current_proposal:
                self.current_proposal.status = "booked"
                self.current_proposal.booking = result
                self.messages.append(
                    ChatMessage(
                        id=f"c_{uuid4().hex[:8]}",
                        kind="celebration",
                        ts=self._now_iso(),
                        text="the group hatched a plan",
                        event_title=self.current_proposal.event.get("title"),
                    )
                )
            self.last_booking = result
            self.nest_warmth = 30  # nest fully restored

    async def skip_proposal(self) -> None:
        async with self.lock:
            if self.current_proposal:
                self.current_proposal.status = "skipped"
                self.current_proposal = None

    async def swap_to_alternate(self, alt_index: int = 0) -> Proposal | None:
        async with self.lock:
            p = self.current_proposal
            if not p or not p.alternates or alt_index >= len(p.alternates):
                return p
            new_event = p.alternates.pop(alt_index)
            p.alternates.append(p.event)
            p.event = new_event
            p.approvals = {uid: False for uid in p.approvals}
            self._add_idea(new_event, source="proposal", score=int(new_event.get("_score", 0)) or 5)
            return p

    async def dismiss_idea(self, event_id: str) -> None:
        """Global removal — used by the booking flow to expel an idea from
        every viewer's panel once it lands in the Booked section. Per-user
        Hide goes through `hide_idea` instead."""
        async with self.lock:
            for i in self.ideas:
                if i.event.get("id") == event_id:
                    i.dismissed = True

    async def hide_idea(self, event_id: str, user_id: str) -> None:
        """Per-user Hide: this viewer no longer sees the idea, but it stays
        visible to everyone else (lower in the rank, since each hider
        subtracts from the composite score)."""
        async with self.lock:
            self._mirror_hide(event_id, user_id, on=True)

    async def propose_idea(
        self, event_id: str, proposer_user_id: str | None = None
    ) -> Proposal | None:
        """Take an idea from the panel and turn it into the current proposal."""
        from datetime import timedelta

        async with self.lock:
            idea = next((i for i in self.ideas if i.event.get("id") == event_id), None)
            if not idea:
                return None
            event = idea.event
            start = datetime.fromisoformat(event["datetime"])
            end = start + timedelta(minutes=event["duration_minutes"])
            user_ids = self._user_ids()
            approvals = {uid: False for uid in user_ids}
            if proposer_user_id in approvals:
                approvals[proposer_user_id] = True
            proposal = Proposal(
                id=f"p_{uuid4().hex[:8]}",
                window={"start": start.isoformat(), "end": end.isoformat()},
                event=event,
                alternates=[],
                approvals=approvals,
                status="pending",
                created_at=self._now_iso(),
            )
            self.current_proposal = proposal
            if proposer_user_id:
                self._mirror_interest(event.get("id"), proposer_user_id, on=True)
            return self.current_proposal

    async def set_warmth(self, days: int) -> int:
        """Directly set the nest-warmth value (0–30). Used by dev time controls."""
        async with self.lock:
            self.nest_warmth = max(0, min(30, int(days)))
            return self.nest_warmth

    def is_cold(self, threshold: int = 3) -> bool:
        return self.nest_warmth <= threshold and self.current_proposal is None

    async def reset(self) -> None:
        async with self.lock:
            self.current_proposal = None
            self.nest_warmth = 6
            self.last_booking = None
            self.ideas = []
            _seed_state(self)


# ──────────────────────── singleton + seed data ────────────────────────


def _seed_messages() -> list[ChatMessage]:
    """Initial dead-chat state for the demo."""
    return [
        ChatMessage(id="m_seed1", kind="user", ts="3 weeks ago", author_id="jono", text="miss y'all 😭"),
        ChatMessage(id="m_seed2", kind="user", ts="3 weeks ago", author_id="andrew", text="we gotta do something soon fr"),
        ChatMessage(id="m_seed3", kind="user", ts="2 weeks ago", author_id="jono", text="down whenever, lmk"),
    ]


def _next_weekday(now: datetime, weekday: int) -> datetime:
    """Next occurrence (strictly future, not today) of `weekday` (Mon=0..Sun=6)."""
    days_ahead = (weekday - now.weekday()) % 7
    if days_ahead == 0:
        days_ahead = 7
    return now + timedelta(days=days_ahead)


def _seed_ideas(now: datetime) -> list[dict]:
    """Three crowd-pleasing LA hangouts, future-dated relative to `now`.

    Routed through `_add_idea` on init/reset so the proactive flow always has
    something to propose, even before any reactive activity. Acts like a
    "popular spots near you" backstop — the agent is never empty-handed.

    Base scores are tuned so Lakers wins the cold-start tiebreak (the canonical
    demo flow), but a single "I'm in" or Hide on any other seed will reorder.
    """
    sat = _next_weekday(now, 5)  # Saturday
    fri = _next_weekday(now, 4)  # Friday
    return [
        {
            "id": "seed_lakers",
            "title": "Los Angeles Lakers vs. Golden State Warriors at Crypto.com Arena",
            "datetime": sat.replace(hour=19, minute=30, second=0, microsecond=0).isoformat(),
            "duration_minutes": 150,
            "location": "Crypto.com Arena, Downtown Los Angeles, Los Angeles",
            "price": 89,
            "tags": ["basketball", "lakers", "sports", "ticketed", "indoor"],
            "venue": "Crypto.com Arena",
            "url": "https://www.google.com/maps/search/?api=1&query=Crypto.com+Arena+Los+Angeles",
            "_score": 5,
        },
        {
            "id": "seed_smorg",
            "title": "Smorgasburg ROW DTLA",
            "datetime": sat.replace(hour=11, minute=0, second=0, microsecond=0).isoformat(),
            "duration_minutes": 180,
            "location": "ROW DTLA, Arts District, Los Angeles",
            "price": 0,
            "tags": ["food", "market", "outdoor", "free", "brunch"],
            "venue": "Smorgasburg ROW DTLA",
            "url": "https://www.google.com/maps/search/?api=1&query=Smorgasburg+ROW+DTLA",
            "_score": 3,
        },
        {
            "id": "seed_lacma",
            "title": "LACMA After Hours: Light & Space",
            "datetime": fri.replace(hour=20, minute=0, second=0, microsecond=0).isoformat(),
            "duration_minutes": 120,
            "location": "LACMA, Mid-Wilshire, Los Angeles",
            "price": 25,
            "tags": ["art", "museum", "evening", "indoor"],
            "venue": "LACMA",
            "url": "https://www.google.com/maps/search/?api=1&query=LACMA+Los+Angeles",
            "_score": 2,
        },
    ]


def _seed_state(state: "GroupState") -> None:
    """Populate a fresh GroupState with seed messages + seed ideas.

    Called from both `store()` (first init) and `GroupState.reset()` (demo
    reset) so a freshly-rebooted demo has the same starting context.
    """
    state.messages = _seed_messages()
    for ev in _seed_ideas(datetime.now(timezone.utc)):
        state._add_idea(ev, source="reactive", score=int(ev.get("_score") or 0))


_state: GroupState | None = None


def store() -> GroupState:
    global _state
    if _state is None:
        _state = GroupState()
        _seed_state(_state)
    return _state
